# Generated by Django 3.2.2 on 2021-05-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.chofer'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.combi'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='main.Insumo'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ruta'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='main.lugar'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='main.lugar'),
        ),
        migrations.AlterUniqueTogether(
            name='lugar',
            unique_together={('localidad', 'provincia')},
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('chofer', 'fecha', 'ruta')},
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('origen', 'destino')},
        ),
    ]
