# Generated by Django 3.2.3 on 2021-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('viajando', 'Viajando'), ('reservado', 'Reservado')], max_length=12),
        ),
    ]
