# Generated by Django 3.2.4 on 2021-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
    ]
