# Generated by Django 3.2 on 2021-05-13 13:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 5, 14))]),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('chofer', 'fecha', 'hora', 'ruta')},
        ),
    ]
