# Generated by Django 3.2.4 on 2021-06-30 20:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('viajando', 'Viajando'), ('perdido', 'Perdido'), ('finalizado', 'Finalizado'), ('reservado', 'Reservado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='estado',
            field=models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='pasajero',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.pasajero'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('viajando', 'Viajando'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 30))]),
        ),
    ]
