# Generated by Django 3.2.4 on 2021-06-24 23:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('viajando', 'Viajando'), ('finalizado', 'Finalizado'), ('reservado', 'Reservado')], max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 24))]),
        ),
    ]
