# Generated by Django 3.2 on 2021-06-29 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('viajando', 'Viajando'), ('reservado', 'Reservado')], max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='estado',
            field=models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
