# Generated by Django 3.2 on 2021-04-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('lugar_salida', models.TimeField()),
                ('lugar_llegada', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='viaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.viaje'),
        ),
        migrations.AddField(
            model_name='combi',
            name='viaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.viaje'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='viaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.viaje'),
        ),
    ]
