# Generated by Django 3.2 on 2021-07-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('super comoda', 'Super Comoda'), ('comoda', 'Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('perdido', 'Perdido'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='estado',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
    ]
