# Generated by Django 3.2 on 2021-06-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210629_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='usuario',
        ),
        migrations.AddField(
            model_name='test',
            name='pasajero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.pasajero'),
        ),
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('comoda', 'Comoda'), ('super comoda', 'Super Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('viajando', 'Viajando'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado')], max_length=12),
        ),
    ]
