# Generated by Django 3.2.4 on 2021-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210629_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado')], default='reservado', max_length=12),
        ),
    ]
