# Generated by Django 3.2 on 2021-06-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210609_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='viaje',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.viaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('super comoda', 'Super Comoda'), ('comoda', 'Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado')], max_length=12),
        ),
    ]
