# Generated by Django 3.2 on 2021-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210426_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
