# Generated by Django 3.2 on 2021-06-02 19:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_combi_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('comoda', 'Comoda'), ('super comoda', 'Super Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 3))]),
        ),
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('finalizado', 'Finalizado'), ('viajando', 'Viajando')], max_length=12)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('fecha', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 3))])),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='viaje',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='main.Comentario'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pasajeros',
            field=models.ManyToManyField(blank=True, to='main.Pasajeros'),
        ),
    ]
