# Generated by Django 3.2.3 on 2021-06-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210609_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('comoda', 'Comoda'), ('super comoda', 'Super Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('viajando', 'Viajando'), ('reservado', 'Reservado')], max_length=12),
        ),
    ]
