# Generated by Django 3.2 on 2021-04-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210426_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='insumo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.insumo'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
    ]
