# Generated by Django 3.2 on 2021-06-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210602_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('viajando', 'Viajando'), ('reservado', 'Reservado')], max_length=12)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pasajeros',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pasajeros',
            field=models.ManyToManyField(blank=True, to='main.Pasajero'),
        ),
    ]
