# Generated by Django 3.2 on 2021-06-03 13:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_viaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 4))]),
        ),
    ]
