# Generated by Django 3.2 on 2021-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210630_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('finalizado', 'Finalizado'), ('viajando', 'Viajando'), ('perdido', 'Perdido'), ('reservado', 'Reservado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='estado',
            field=models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('viajando', 'Viajando'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado')], default='reservado', max_length=12),
        ),
    ]
