# Generated by Django 3.2.4 on 2021-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210629_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('super comoda', 'Super Comoda'), ('comoda', 'Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('perdido', 'Perdido'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado')], default='reservado', max_length=12),
        ),
    ]
