# Generated by Django 3.2 on 2021-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210630_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('comoda', 'Comoda'), ('super comoda', 'Super Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('perdido', 'Perdido'), ('viajando', 'Viajando'), ('reservado', 'Reservado')], default='reservado', max_length=12),
        ),
    ]
