# Generated by Django 3.2.4 on 2021-06-29 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210629_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('comoda', 'Comoda'), ('super comoda', 'Super Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('perdido', 'Perdido'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado'), ('reservado', 'Reservado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
        migrations.CreateModel(
            name='TestPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=12)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajes', models.ManyToManyField(to='main.Viaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
