# Generated by Django 3.2.3 on 2021-06-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210610_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('viajando', 'Viajando'), ('finalizado', 'Finalizado')], max_length=12),
        ),
    ]
