# Generated by Django 3.2 on 2021-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210630_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('perdido', 'Perdido'), ('reservado', 'Reservado'), ('viajando', 'Viajando')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('reservado', 'Reservado'), ('viajando', 'Viajando'), ('cancelado', 'Cancelado')], default='reservado', max_length=12),
        ),
    ]
