# Generated by Django 3.2 on 2021-05-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210503_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='main.lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.lugar'),
        ),
    ]
