# Generated by Django 3.2 on 2021-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210610_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('super comoda', 'Super Comoda'), ('comoda', 'Comoda')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='estado',
            field=models.CharField(choices=[('viajando', 'Viajando'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado')], max_length=12),
        ),
    ]
