# Generated by Django 3.2.3 on 2021-06-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pasajero_estado'),
        ('main', '0011_auto_20210610_0213'),
    ]

    operations = [
    ]
