# Generated by Django 3.2 on 2021-05-12 12:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210511_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='main.lugar', unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='main.lugar', unique=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 5, 13))]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='main.Insumo'),
        ),
    ]
