# Generated by Django 3.2 on 2021-06-30 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=19, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('fecha', models.DateField()),
                ('titular', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='tarjetas',
            field=models.ManyToManyField(blank=True, to='users.Tarjeta'),
        ),
    ]
