# Generated by Django 3.2 on 2021-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210630_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha',
            field=models.CharField(max_length=40),
        ),
    ]
