# Generated by Django 3.2.3 on 2021-06-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_has_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_premium',
            field=models.BooleanField(default=False, verbose_name='Posee membresía premium'),
        ),
    ]
