# Generated by Django 3.2 on 2021-06-30 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tarjeta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
